const {chromium}=require('playwright');const assert=require('assert');
(async()=>{const browser=await chromium.launch();const c=await browser.newContext({viewport:{width:1440,height:1000}});const email='geo-test@example.invalid',id='40000000-0000-4000-8000-000000000001';let meta={city:'Ростовская область, г Новочеркасск, ул Маресьева, д 36'},patch=null,profile=null,fail=false,admin=true,calls=[];
const place=(city='Воронеж')=>({type:'Feature',properties:{countrycode:'RU',name:city,osm_key:'place',osm_value:'city',type:'city',state:'Воронежская область'},geometry:{coordinates:[39.2,51.7]}});
const house=()=>({type:'Feature',properties:{countrycode:'RU',city:'Воронеж',street:'улица Ленина',housenumber:'36',state:'Воронежская область',type:'house'},geometry:{coordinates:[39.21,51.71]}});
await c.route('https://photon.komoot.io/**',async r=>{const u=new URL(r.request().url());calls.push(u);assert.equal(u.searchParams.get('lang'),'default');assert.equal(u.searchParams.get('countrycode'),'RU');assert(!r.request().headers().authorization);if(fail){await r.fulfill({status:403,body:'Forbidden'});return;}
const city=u.searchParams.getAll('layer').includes('city');await r.fulfill({json:{features:city?[place(),place(),{properties:{countrycode:'DE',name:'Berlin',type:'city'}},{properties:{countrycode:'RU',city:'Voronezh',type:'city',name:'Voronezh'}}]:[house()]}});});
await c.route('https://*.supabase.co/**',async r=>{const req=r.request(),u=new URL(req.url());let data=[];
if(u.pathname==='/auth/v1/user'){if(req.method()==='PUT')meta={...meta,...JSON.parse(req.postData()).data};data={id:'50000000-0000-4000-8000-000000000001',email,user_metadata:meta};}
else if(u.pathname.endsWith('/admins'))data=admin?[{email,active:true,role:'admin',company:'Прокат',full_name:'Контакт',phone:'+79001234567'}]:[];
else if(u.pathname.endsWith('/tools')){if(req.method()==='PATCH'){patch=JSON.parse(req.postData());data=[{id,owner_email:email,status:'active',...patch}];}else data=[{id,owner_email:email,status:'active',active:true,name:'Дрель без запятой',cat:'power',sub:'drills',price:300,deposit:0,imgs:['https://example.invalid/test.jpg'],descr:'Описание инструмента для теста геоподсказок.',terms:'Адрес выдачи: Новочеркасск Маресьева 36'},{id:'other',owner_email:email,status:'active',active:true,name:'Дрель Воронеж',cat:'power',price:400,pickup_city:'Воронеж',terms:'Адрес выдачи: улица Ленина, дом 36'}];if(u.searchParams.has('id'))data=data.filter(x=>'eq.'+x.id===u.searchParams.get('id'));}
else if(u.pathname.endsWith('/cats'))data=[{key:'power',title:'Электроинструмент'}];
else if(u.pathname.endsWith('/subcats'))data=[{key:'drills',cat:'power',title:'Дрели'}];
else if(u.pathname.endsWith('/landlord_profiles'))data=profile?[profile]:[];
else if(u.pathname.endsWith('/rpc/save_landlord_profile')){const body=JSON.parse(req.postData());profile={details:body.p_details,locations:body.p_locations,revision:1};data=profile;}
await r.fulfill({json:data});});
const p=await c.newPage();let errors=[];p.on('pageerror',e=>errors.push(e.message));p.on('dialog',d=>d.accept());
const go=async(path='')=>{await p.goto('http://127.0.0.1:8000/'+path);await p.waitForLoadState('networkidle');};
await go();await p.evaluate(()=>localStorage.setItem('iva_sess',JSON.stringify({tok:'mock',rtok:'mock-refresh'})));await go();assert.equal(await p.locator('.city-name').textContent(),'Новочеркасск');assert.equal(await p.locator('#grid .ad').count(),1);
assert.deepEqual(await p.evaluate(()=>['Новочеркасск Маресьева 36','Ростовская область, г. Ростов-на-Дону, ул. Ленина, 7','Новочеркасское шоссе','улица Ленина, 36'].map(IvaGeo.addressCity)),['Новочеркасск','Ростов-на-Дону','','']);
// Debounce and keyboard city selection. Only the city goes into the header/filter.
await p.locator('#cityBtn').click();await p.locator('#citySearch').fill('В');await p.locator('#citySearch').fill('Во');await p.locator('#citySearch').fill('Воро');await p.waitForFunction(()=>document.querySelector('#citySearch').closest('.geo-wrap').querySelector('[role=option] small')?.textContent==='Воронежская область');assert.equal(calls.length,1);assert.equal(await p.locator('#citySearch').locator('..').locator('[role=option]').count(),1);await p.locator('#citySearch').press('ArrowDown');await p.locator('#citySearch').press('Enter');await p.waitForSelector('#sheet',{state:'detached'});assert.equal(await p.locator('.city-name').textContent(),'Воронеж');assert.equal(await p.locator('#grid .ad').count(),1);assert.equal(await p.locator('#grid .rnm').count(),0);
// Sidebar field, local city variants, cache and explicit address URL normalization.
await p.locator('#filters .geo-filter-city').fill('Воро');await p.waitForFunction(()=>document.querySelector('#filters .geo-panel:not([hidden]) [role=option] small')?.textContent==='Воронежская область');assert.equal(calls.length,1);await p.locator('#filters .geo-option').first().click();
await go('catalog.html?city='+encodeURIComponent('Новочеркасск, ул. Маресьева, 36'));assert.equal(await p.locator('.city-name').textContent(),'Новочеркасск');assert.equal(await p.locator('#grid .ad').count(),1);
await go('new.html?edit='+id);await p.locator('#bNext').click();await p.locator('#bNext').click();assert.equal(await p.locator('#iCity').inputValue(),'Новочеркасск');assert((await p.locator('#root').textContent()).includes('доступен всем посетителям'));
await p.locator('#iCity').fill('Воронеж');await p.locator('#iAddr').fill('Воронеж Ленина 36');await p.waitForFunction(()=>document.querySelector('#iAddr').closest('.geo-wrap').textContent.includes('улица Ленина'));await p.locator('#iAddr').locator('..').locator('.geo-option').first().click();assert.equal(await p.locator('#iCity').inputValue(),'Воронеж');assert.equal(await p.locator('#iAddr').inputValue(),'Воронеж, улица Ленина, д. 36');await p.locator('#bSave').click();await p.waitForSelector('#root .empty');assert.equal(patch.pickup_city,'Воронеж');assert(patch.terms.includes('Адрес выдачи: Воронеж, улица Ленина, д. 36'));assert(!('status'in patch));
// Point selection updates its city, not the profile/default/header city.
await go('account.html#prof');await p.locator('#editRental').click();await p.locator('#addPoint').click();await p.locator('[name=point-name]').fill('Новая точка');await p.locator('[name=point-address]').fill('Воронеж Ленина 36');await p.waitForFunction(()=>document.querySelector('[name=point-address]').closest('.geo-wrap').textContent.includes('улица Ленина'));await p.locator('[name=point-address]').locator('..').locator('.geo-option').first().click();assert.equal(await p.locator('[name=point-city]').inputValue(),'Воронеж');await p.locator('#saveRental').click();await p.waitForSelector('#editRental');assert.equal(profile.locations[0].city,'Воронеж');assert(profile.locations[0].address.includes('д. 36'));assert.equal(await p.locator('.city-name').textContent(),'Новочеркасск');
// Provider failure still allows manual city selection and Russian feedback.
fail=true;await p.locator('#cityBtn').click();await p.locator('#citySearch').fill('Псков');await p.waitForFunction(()=>document.querySelector('#citySearch').closest('.geo-wrap').textContent.includes('временно недоступны'));await p.locator('#citySearchForm button').click();await p.waitForSelector('#sheet',{state:'detached'});assert.equal(await p.locator('.city-name').textContent(),'Псков');
// All relevant controls have attached Russian autocomplete, including registration.
admin=false;await go('landlord-register.html');await p.waitForSelector('#laCity');assert.equal(await p.locator('#laCity').getAttribute('role'),'combobox');assert.equal(await p.locator('#laRegion').getAttribute('role'),'combobox');
await p.setViewportSize({width:390,height:844});await go('account.html#prof');await p.locator('#profileCity').fill('Тверь');await p.waitForFunction(()=>document.querySelector('#profileCity').closest('.geo-wrap').textContent.includes('временно недоступны'));assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await p.locator('#profileCityForm button').click();await p.waitForFunction(()=>document.querySelector('.city-name').textContent==='Тверь');assert.equal(meta.city,'Тверь');
assert.deepEqual(errors,[]);console.log('PASS: Photon query/language/country/no auth leakage, debounce/cache, Russian results, deduplication, city-only header/sidebar/URL, no-comma legacy address, explicit listing city, point-city sync, keyboard/mobile, manual fallback and registration.');await browser.close();})();
