const {chromium}=require('playwright');const assert=require('assert');
(async()=>{const b=await chromium.launch();const c=await b.newContext({viewport:{width:1440,height:1000}});let profile=null,fail=false,conflict=false,failLoad=false,admin=true,saves=0;const email='qa-rental@example.invalid';let meta={name:'Тестовый владелец',city:'Ростов-на-Дону',phone:'+79001112233'};
await c.route('https://*.supabase.co/**',async route=>{const r=route.request(),u=new URL(r.url());let data=[];
if(u.pathname==='/auth/v1/user'){if(r.method()==='PUT')meta={...meta,...JSON.parse(r.postData()).data};data={id:'30000000-0000-4000-8000-000000000001',email,user_metadata:meta};}
else if(u.pathname.endsWith('/admins'))data=admin?[{email,role:'admin',active:true,fee_pct:7,debt_limit:5000,company:'Прокат у дома',full_name:'Контакт из анкеты',phone:'+79001112233',address:'Ростов-на-Дону, ул. Старая, 1',work_hours:'Пн–Пт 09:00–18:00'}]:[];
else if(u.pathname.endsWith('/landlord_applications'))data=[{city:'Ростов-на-Дону',status:'approved',business_type:'sole_trader',company:'ИП Тестов'}];
else if(u.pathname.endsWith('/landlord_profiles')){if(failLoad){await route.fulfill({status:500,json:{message:'Ошибка чтения'}});return;}data=profile?[profile]:[];}
else if(u.pathname.endsWith('/rpc/save_landlord_profile')){saves++;const d=JSON.parse(r.postData());assert.deepEqual(Object.keys(d).sort(),['p_details','p_locations','p_revision']);assert(!('role' in d.p_details));assert(!('fee_pct' in d.p_details));assert(!('owner_email' in d.p_details));if(fail||conflict){await route.fulfill({status:400,json:{message:conflict?'Профиль изменён в другой вкладке':'Тестовый сбой'}});return;}assert.equal(d.p_revision,profile?profile.revision:0);profile={owner_email:email,details:d.p_details,locations:d.p_locations,revision:d.p_revision+1};data=profile;}
else if(u.pathname.endsWith('/tools'))data=[{id:'tool-test',name:'Тестовая дрель',cat:'power',price:300,deposit:0,owner_email:email,status:'active',active:true,terms:'Адрес выдачи: Ростов-на-Дону, ул. Старая, 1',imgs:[]}];
else if(u.pathname.endsWith('/cats'))data=[{key:'power',title:'Электроинструмент',active:true}];
await route.fulfill({json:data});});
const p=await c.newPage();const errors=[];p.on('pageerror',e=>errors.push(e.message));p.on('dialog',d=>d.accept());
await p.goto('http://127.0.0.1:8000/');await p.evaluate(email=>localStorage.setItem('iva_auth',JSON.stringify({tok:'test-token',ref:'test-refresh',exp:9999999999999})),email);
const go=async(path='account.html#prof')=>{await p.goto('http://127.0.0.1:8000/'+path);await p.reload();await p.waitForLoadState('networkidle');};
await go('cabinet.html#cab');await p.waitForURL('**/account.html#prof');await p.waitForSelector('#editRental');assert((await p.locator('#rentalProfile').textContent()).includes('Лимит задолженности'));assert((await p.locator('#rentalProfile').textContent()).includes('5 000 ₽'));
await p.locator('#editRental').click();assert.equal(await p.locator('[name=display_name]').inputValue(),'Прокат у дома');assert.equal(await p.locator('[data-point]').count(),1);assert.equal(await p.locator('[name=point-phone]').getAttribute('required'),null);
await p.locator('[name=display_name]').fill('Прокат «Тест»');await p.locator('[name=description]').fill('Инструмент для дома и стройки. <img src=x onerror=alert(1)>');await p.locator('[name=public_email]').fill('rent@example.invalid');assert.equal(await p.locator('[name=website]').count(),0);assert.equal(await p.locator('[name=vk]').count(),0);assert((await p.locator('#rp-delivery').textContent()).includes('Данные, которые указываются в этом пункте'));await p.locator('[name=delivery_area]').fill('Ростов-на-Дону, Шахты');await p.locator('[name=deposit_terms]').fill('Залог по договору');
await p.locator('#addPoint').click();let point=p.locator('[data-point]').nth(1);await point.locator('[name=point-name]').fill('Склад в Шахтах');await point.locator('[name=point-city]').fill('Шахты');await point.locator('[name=point-address]').fill('ул. Новая, 2');await point.locator('[name=point-hours]').fill('Ежедневно 10:00–19:00');await point.locator('[name=point-directions]').fill('Вход со двора');await point.locator('[data-primary]').click();assert.equal(await p.locator('[data-point]').first().locator('[name=point-city]').inputValue(),'Шахты');
await p.locator('#saveRental').click();await p.waitForSelector('#editRental');assert.equal(profile.locations.length,2);assert.equal(profile.locations[0].city,'Шахты');assert.equal(await p.locator('#rentalProfile img').count(),0);assert.equal(meta.city,'Ростов-на-Дону');assert.equal(await p.locator('.city-name').textContent(),'Ростов-на-Дону');
await go();await p.locator('#editRental').click();assert.equal(await p.locator('[name=description]').inputValue(),profile.details.description);assert.equal(await p.locator('[data-point]').count(),2);
await p.locator('[name=description]').fill('Не потерять правки');await p.locator('#profileCity').fill('Таганрог');await p.locator('#profileCityForm button').click();await p.waitForFunction(()=>document.querySelector('.city-name').textContent==='Таганрог');assert.equal(await p.locator('[name=description]').inputValue(),'Не потерять правки');
fail=true;await p.locator('#saveRental').click();await p.waitForFunction(()=>!document.querySelector('#saveRental').disabled);assert((await p.locator('#rentalError').textContent()).includes('Тестовый сбой'));assert.equal(await p.locator('[name=description]').inputValue(),'Не потерять правки');fail=false;conflict=true;await p.locator('#saveRental').click();await p.waitForFunction(()=>!document.querySelector('#saveRental').disabled);assert((await p.locator('#rentalError').textContent()).includes('другой вкладке'));conflict=false;
await p.locator('[data-remove]').first().click();await p.locator('#saveRental').click();await p.waitForSelector('#editRental');assert.equal(profile.locations.length,1);await go();await p.locator('#editRental').click();assert.equal(await p.locator('[data-point]').count(),1);
await p.locator('[name=phone]').fill('123');let n=saves;await p.locator('#saveRental').click();assert.equal(saves,n);assert((await p.locator('#rentalError').textContent()).includes('телефоны'));await p.locator('#cancelRental').click();
for(const width of [390,768,1440]){await p.setViewportSize({width,height:1000});assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await p.locator('#editRental').click();assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await p.locator('#cancelRental').click();}
await p.setViewportSize({width:1440,height:1000});failLoad=true;await go();assert.equal(await p.locator('#editRental').count(),0);assert((await p.locator('#rentalProfile').textContent()).includes('Ошибка чтения'));failLoad=false;await p.locator('#rentalProfile button').click();await p.waitForSelector('#editRental');
// Saved public contacts and exact addresses are visible without auth; no private fee/limits.
await p.evaluate(()=>{localStorage.removeItem('iva_sess');localStorage.removeItem('iva_auth');});await go('tool.html?id=tool-test');assert((await p.locator('.public-pickups').textContent()).includes('rent@example.invalid'));await p.locator('.public-pickups summary').click();assert((await p.locator('.public-pickups').textContent()).includes('ул. Старая, 1'));assert(!(await p.locator('.public-pickups').textContent()).includes('5000'));
// A non-landlord only edits personal metadata, never sees business editor.
admin=false;await p.evaluate(()=>localStorage.setItem('iva_sess',JSON.stringify({tok:'test',rtok:'test-refresh'})));await go();assert.equal(await p.locator('#rentalProfile').count(),0);await p.locator('#editPersonal').click();await p.locator('#personalForm [name=name]').fill('Новое имя');await p.locator('#personalForm button').click();await p.waitForSelector('#personalForm',{state:'detached'});assert.equal(meta.city,'Таганрог');assert.equal(meta.name,'Новое имя');await p.locator('#bOut').click();assert.equal(await p.evaluate(()=>localStorage.getItem('iva_auth')),null);assert.equal(await p.evaluate(()=>localStorage.getItem('iva_sess')),null);
assert.deepEqual(errors,[]);console.log('PASS: legacy route/session bridge, role-based profile, prefill, multi-city locations, primary/delete/reload, public data and XSS escaping, profile-city isolation, validation, save failures/conflicts, loading failure, responsive layout, personal editor and logout.');await b.close();})();
