-- ============================================================================
-- Ива — счётчик обращений со страниц городов (этап П3). Только добавление.
-- Дата: 2026-10-01
--
-- Что делает: создаёт таблицу для подсчёта, сколько раз со страниц городов
-- звонили в пункты проката (kind='call'), звали нашу помощь (kind='lead') и
-- сколько было показов страницы (kind='view').
--
-- ПЕРСОНАЛЬНЫХ ДАННЫХ НЕТ: не сохраняется ни IP, ни cookie, ни отпечаток
-- браузера — только телефон пункта (он и так опубликован), город, имя страницы,
-- тип обращения и время. Данные посетителя не записываются.
--
-- Как запускать: Supabase -> SQL Editor -> New query -> вставить -> Run.
-- Повторный запуск безопасен. Ничего не удаляет и не меняет.
-- Если не запускать — страницы городов работают как обычно, просто без статистики.
--
-- Откат: см. блок в конце файла.
-- ============================================================================

create table if not exists public.directory_clicks (
  id         bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  phone      text not null default '',
  city       text not null default '',
  page       text not null default '',
  kind       text not null default 'call'
);

-- Ограничения на входящие данные: телефон — только цифры, типы — известные,
-- строки — разумной длины. Это защита от мусора, который может прислать кто угодно
-- (запись открыта с публичной страницы, иначе счётчик не работал бы).
alter table public.directory_clicks drop constraint if exists directory_clicks_kind_check;
alter table public.directory_clicks
  add constraint directory_clicks_kind_check check (kind in ('call', 'lead', 'view'));
alter table public.directory_clicks drop constraint if exists directory_clicks_phone_check;
alter table public.directory_clicks
  add constraint directory_clicks_phone_check check (phone = '' or phone ~ '^[0-9]{10,15}$');
alter table public.directory_clicks drop constraint if exists directory_clicks_len_check;
alter table public.directory_clicks
  add constraint directory_clicks_len_check check (char_length(city) <= 80 and char_length(page) <= 80);

create index if not exists idx_directory_clicks_created on public.directory_clicks (created_at);
create index if not exists idx_directory_clicks_phone   on public.directory_clicks (phone);
create index if not exists idx_directory_clicks_kind    on public.directory_clicks (kind);

-- Правила доступа:
--   • добавить запись может страница сайта (иначе счётчик не работает);
--   • читать строки — только администраторы (в кабинете главного);
--   • для отчётов есть отдельная сводка без строк (ниже).
alter table public.directory_clicks enable row level security;

drop policy if exists "directory_clicks_insert_public" on public.directory_clicks;
create policy "directory_clicks_insert_public" on public.directory_clicks
  for insert to anon, authenticated
  with check (true);

drop policy if exists "directory_clicks_select_admins" on public.directory_clicks;
create policy "directory_clicks_select_admins" on public.directory_clicks
  for select to authenticated
  using (
    exists (
      select 1 from public.admins
      where lower(email) = lower(auth.jwt() ->> 'email') and active = true
    )
  );

-- Сводка для отчётов: только итоги (сколько обращений по пунктам и дням),
-- без строк и без возможности что-то изменить. Наружу не отдаётся: сводку видит
-- только администратор в кабинете — чтобы объёмы обращений не были видны конкурентам.
-- security_invoker = true означает, что правила доступа таблицы применяются к тому,
-- кто спрашивает: администратор — видит, посторонний — нет.
create or replace view public.directory_click_stats
with (security_invoker = true) as
select
  phone,
  city,
  kind,
  date_trunc('day', created_at)::date as day,
  count(*) as cnt
from public.directory_clicks
group by 1, 2, 3, 4;

revoke all on public.directory_click_stats from anon;
grant select on public.directory_click_stats to authenticated;

-- ============================================================================
-- Откат (раскомментировать и запустить, если решишь убрать статистику):
-- ============================================================================
-- drop view  if exists public.directory_click_stats;
-- drop table if exists public.directory_clicks;
